"use client";
import { useState } from "react";
import { ToggleGroup, ToggleGroupItem } from "@/components/ui/toggle-group";
import { Accordion, AccordionItem, AccordionTrigger, AccordionContent } from "@/components/ui/accordion";
import { Code2, Database, GitBranch, CheckCheck, Menu, X, Download, Mail, ExternalLink, ShieldCheck, FileCheck2 } from "lucide-react";

const cases = [
 {id:'citi',company:'Citi',domain:'Issuer Services · Banking',title:'New language. Same business rules.',intro:'Checking that automated ADR tests kept their intended behaviour through a Python-to-Java migration.',tags:['Automation','AI-assisted testing'],tools:['Java','Selenium','FAST Framework','Devin AI','Zephyr'],visual:'migration',context:'The American Depositary Receipts (ADR) application in Issuer Services was moving automated tests from Python to Java. The converted tests needed to preserve the business rules and assertions in the original suite.',actions:['Converted Python test scripts to Java using Citi’s FAST Framework and Selenium libraries.','Reviewed Devin AI-generated code to check business rules and assertions.','Executed migrated suites, compared results with the Python tests and investigated differences.','Recorded execution results, defects and retest outcomes in Zephyr.'],outcome:'Maintained regression coverage through the migration and kept unresolved issues traceable through execution and retesting.'},
 {id:'blueface',company:'Blueface',domain:'Portal · Web & desktop applications',title:'Less repetition. More regression coverage.',intro:'Python and Robot Framework tests for web workflows and REST APIs, with feedback through GitHub Actions.',tags:['Automation','API & data'],tools:['Python','Robot Framework','REST APIs','GitHub Actions'],visual:'coverage',context:'Changes to the Blueface Portal and its connected services required checks across user workflows, API behaviour and backend integrations.',actions:['Turned requirements and acceptance criteria into test scenarios for critical workflows.','Developed and maintained automated tests for web applications and REST APIs.','Checked authentication, JSON payloads, business rules and integrations using Postman, Swagger and Robot Framework.','Integrated regression suites into GitHub Actions and investigated failures using logs and execution results.'],outcome:'Achieved 90% automated regression coverage and reduced manual regression effort by around 30%.'},
 {id:'ideative',company:'Ideative',domain:'LIMS · E-commerce web applications',title:'A reusable foundation for changing workflows.',intro:'Page objects, 700+ automated UI tests and SQL checks across LIMS and e-commerce applications.',tags:['Automation','API & data'],tools:['Python','Selenium','Pytest-BDD','Jenkins','SQL'],visual:'pipeline',context:'LIMS and e-commerce applications needed repeatable checks as features and business workflows changed, including validation of data across integrated systems.',actions:['Developed and maintained 700+ UI tests using Python, Selenium, Pytest-BDD and Page Object Model.','Configured Jenkins regression jobs and reviewed failed runs before release.','Used SQL to validate backend data accuracy and consistency.','Planned regression coverage with developers and product owners, clarifying requirements and preparing test data.'],outcome:'Expanded reusable UI regression coverage, reduced repeated manual testing and checked data consistency across integrated systems.'}
];
const roles=[
 {date:'Jan 2026 – Feb 2026',company:'Citi',role:'Intermediate Programmer Analyst (SDET)',place:'Dublin, Ireland',text:'Issuer Services · American Depositary Receipts (ADR)',points:['Converted automated tests from Python to Java using FAST Framework and Selenium libraries.','Reviewed Devin AI-generated Java code, investigated execution differences and tracked regression results and retests in Zephyr.']},
 {date:'Mar 2022 – May 2024',company:'Blueface',role:'Senior QA Engineer',place:'Ireland · A Comcast Business Company',text:'Blueface Portal · Web, desktop and connected services',points:['Built Python and Robot Framework suites for web and REST APIs, reaching 90% automated regression coverage.','Integrated automated checks into GitHub Actions and investigated defects with developers.','Combined automation with manual functional, integration, exploratory and end-to-end testing, including Android and iOS devices.']},
 {date:'Jun 2016 – Feb 2019',company:'Ideative Digital',role:'Test Engineer',place:'India',text:'LIMS · E-commerce web applications',points:['Developed and maintained 700+ automated UI tests with Python, Selenium, Pytest-BDD and page objects.','Configured Jenkins regression jobs and validated backend data using SQL.','Automated Java and Selenium workflows during an e-commerce internship.']}
];
const skills=[
 {icon:Code2,title:'Languages & automation',items:'Python · Java · Selenium WebDriver · Robot Framework · Pytest · Pytest-BDD · Gherkin · Page Object Model · Citi FAST Framework'},
 {icon:Database,title:'API & data validation',items:'REST APIs · Postman · Swagger · SQL · PostgreSQL · MySQL · SQL Server · Data integrity validation'},
 {icon:GitBranch,title:'CI/CD & collaboration',items:'GitHub Actions · Jenkins · Git · Bitbucket · Jira · Zephyr · TestRail · Confluence'},
 {icon:FileCheck2,title:'Test design & investigation',items:'Requirements and acceptance criteria · Test scenarios and data · Regression · Integration · System · Exploratory · Smoke · UAT · Risk-based testing · Root cause analysis'}
];
export default function Home(){
 const [filter,setFilter]=useState('All work');const [menu,setMenu]=useState(false);const [emailStatus,setEmailStatus]=useState('');
 const visible=cases.filter(c=>filter==='All work'||c.tags.includes(filter));
 return <><a className="skip" href="#main">Skip to content</a><header className="site-header"><a className="brand" href="#top" aria-label="Sravanthi Sunnam, home"><span className="monogram">ss<span>.</span></span><span>SRAVANTHI<br/>SUNNAM</span></a><button className="menu-button" aria-expanded={menu} aria-controls="navigation" onClick={()=>setMenu(!menu)} aria-label={menu?'Close navigation':'Open navigation'}>{menu?<X/>:<Menu/>}</button><nav id="navigation" className={menu?'open':''} aria-label="Main navigation">{[['About','about'],['Selected work','work'],['Experience','experience'],['Skills','skills'],['Learning','learning']].map(([name,id])=><a key={id} href={'#'+id} onClick={()=>setMenu(false)}>{name}</a>)}<a className="nav-contact" href="#contact" onClick={()=>setMenu(false)}>Let’s connect</a></nav></header>
 <main id="main"><section id="top" className="hero section-shell"><div className="hero-copy"><p className="eyebrow"><span className="availability"/>DUBLIN, IRELAND · OPEN TO SDET & QA ROLES</p><p className="hero-name">Hi, I’m Sravanthi.</p><h1>I build tests.<br/>I question<br/><em>the results.</em></h1><p className="hero-description">QA automation engineer with five years in web, API and manual mobile testing. I turn requirements into automated checks, investigate failures and help teams decide what is ready to release.</p><div className="hero-actions"><a className="button primary" href="#work">Explore my work</a><a className="button secondary" href="/assets/Sravanthi-Sunnam-CV.pdf" download><Download size={17}/>Download CV</a></div><p className="hero-stack">PYTHON / JAVA / API TESTING / CI/CD</p></div><div className="hero-portrait"><div className="portrait-frame"><img src="/assets/sravanthi.webp" alt="Sravanthi Sunnam" width="413" height="531" fetchPriority="high"/><div className="portrait-caption"><ShieldCheck size={22}/><div><strong>ISTQB certified</strong><span>Software testing & automation</span></div></div></div><div className="portrait-note"><span>MY APPROACH</span><p>Understand the workflow.<br/>Check the behaviour.<br/>Follow the failure.</p></div></div></section>
 <div className="metrics-band"><div className="metrics section-shell"><div><strong>5<span> years</span></strong><p>Manual & automated testing</p></div><div><strong>90<span>%</span></strong><p>Automated regression coverage<br/><span>Blueface</span></p></div><div><strong>~30<span>%</span></strong><p>Less manual regression effort<br/><span>Blueface</span></p></div><div><strong>700<span>+</span></strong><p>Automated UI tests<br/><span>Ideative</span></p></div></div></div>
 <section id="about" className="section-shell section-space about"><div><p className="eyebrow">THE PERSON BEHIND THE TESTS</p><h2>Curious about the details.<br/><em>Focused on the user.</em></h2></div><div className="about-copy"><p className="lead">A failed test gives me a starting point. I want to understand what changed, which workflow it affects and what the team needs to fix.</p><p>My work spans Citi’s ADR application, the Blueface Portal, and LIMS and e-commerce applications at Ideative. I combine automation with exploratory testing and data checks to understand what happens beyond the expected path.</p><p>I’m now focusing on SDET opportunities where I can build maintainable tests, investigate problems with developers and keep release decisions grounded in the results.</p><div className="qualification-line"><span>MSc Data Analytics</span><span>Dublin Business School · 2020</span></div></div></section>
 <section id="work" className="work-section"><div className="section-shell section-space"><div className="section-top"><div><p className="eyebrow">SELECTED WORK</p><h2>The workflows.<br/><em>The checks behind them.</em></h2></div><p>Three case studies from my professional experience in banking, telecoms and business applications.</p></div><ToggleGroup type="single" value={filter} onValueChange={v=>v&&setFilter(v)} className="work-filters" spacing={2} aria-label="Filter case studies">{['All work','Automation','API & data','AI-assisted testing'].map(x=><ToggleGroupItem key={x} value={x} className="filter-button">{x}</ToggleGroupItem>)}</ToggleGroup><p className="sr-only" role="status">{visible.length} case {visible.length===1?'study':'studies'} shown</p><div className="case-grid">{visible.map((c)=><article className={'case-card '+c.visual} key={c.id}><div className="case-graphic" aria-label={c.visual==='migration'?'Python to Java migration with review of assertions':c.visual==='coverage'?'90% automated regression coverage at Blueface':'UI tests, Jenkins runs and SQL data checks'}><span className="graphic-label">{c.company.toUpperCase()} / {c.visual==='migration'?'TEST MIGRATION':c.visual==='coverage'?'REGRESSION COVERAGE':'TEST FOUNDATION'}</span>{c.visual==='migration'?<div className="migration-diagram"><span>Python</span><span className="migration-line">to</span><span>Java</span><small><CheckCheck size={16}/>Business rules & assertions</small></div>:c.visual==='coverage'?<div className="coverage-diagram"><strong>90<span>%</span></strong><div className="coverage-track"><i/></div><small>Automated regression coverage</small></div>:<div className="pipeline-diagram"><span><Code2 size={18}/>UI tests</span><span><GitBranch size={18}/>Jenkins</span><span><Database size={18}/>SQL checks</span></div>}</div><div className="case-body"><p className="case-company">{c.company} <span>· {c.domain}</span></p><h3>{c.title}</h3><p>{c.intro}</p><div className="tool-tags">{c.tools.map(t=><span key={t}>{t}</span>)}</div><Accordion type="single" collapsible><AccordionItem value={c.id}><AccordionTrigger className="case-trigger">Read the case study</AccordionTrigger><AccordionContent className="case-detail"><h4>The challenge</h4><p>{c.context}</p><h4>My contribution</h4><ul>{c.actions.map(x=><li key={x}>{x}</li>)}</ul><h4>The result</h4><p>{c.outcome}</p></AccordionContent></AccordionItem></Accordion></div></article>)}</div><p className="work-note">Employment case studies. Employer source code and confidential data are not shared.</p></div></section>
 <section id="experience" className="section-shell section-space"><div className="section-top"><div><p className="eyebrow">EXPERIENCE</p><h2>Grounded in<br/><em>real delivery.</em></h2></div><a className="text-link" href="/assets/Sravanthi-Sunnam-CV.pdf" download>Download my full CV</a></div><div className="experience-list">{roles.map(r=><article className="role" key={r.company}><div className="role-date">{r.date}<span>{r.place}</span></div><div className="role-heading"><h3>{r.company}</h3><p className="role-title">{r.role}</p><p className="role-domain">{r.text}</p></div><ul>{r.points.map(x=><li key={x}>{x}</li>)}</ul></article>)}</div><div className="recognition"><ShieldCheck/><p><strong>Top Performer recognition</strong><span>For meeting sprint testing commitments and identifying defects before release.</span></p></div></section>
 <section id="skills" className="skills-section"><div className="section-shell section-space"><div className="section-top"><div><p className="eyebrow">SKILLS & PRACTICE</p><h2>Tools I use.<br/><em>Judgement I bring.</em></h2></div><p>Automation, investigation and clear test evidence, supported by Agile/Scrum, BDD, SDLC and STLC practices.</p></div><div className="skill-grid">{skills.map(s=><article className="skill" key={s.title}><s.icon size={25}/><h3>{s.title}</h3><p>{s.items}</p></article>)}</div><div className="ai-panel"><div><p className="eyebrow">AI-ASSISTED TESTING</p><h3>Checking what the<br/>generated test proves.</h3><div className="tool-tags"><span>Devin AI</span><span>GitHub Copilot</span></div></div><div><p>At Citi, I reviewed Java code generated with Devin AI during the move from Python. I checked business rules and assertions, then compared test behaviour against the original suite.</p><p className="ai-emphasis">The review matters as much as the conversion.</p></div></div><div className="skill-notes"><p><strong>Completed training</strong>Playwright with Python through Udemy, including page objects, fixtures, API testing and reporting.</p><p><strong>Mobile testing</strong>Manual functional testing on Android and iOS devices.</p></div></div></section>
 <section id="learning" className="section-shell section-space"><div className="section-top"><div><p className="eyebrow">CERTIFICATIONS & LEARNING</p><h2>Building on<br/><em>the foundations.</em></h2></div><a className="text-link" href="https://www.linkedin.com/in/sravanthi-sunnam/" target="_blank" rel="noopener noreferrer">View my LinkedIn profile</a></div><div className="credential-grid"><article className="credential"><div className="credential-logo"><img src="/assets/logos/istqb.png" alt="ISTQB" loading="lazy"/></div><span className="credential-type">PROFESSIONAL CERTIFICATION</span><h3>Certified Tester Foundation Level</h3><p>ISTQB · Software testing principles and practice</p></article><article className="credential"><div className="credential-wordmark">Udemy<span> / Python</span></div><span className="credential-type">COMPLETED TRAINING</span><h3>Playwright Python Automation Testing</h3><p>From Zero to Expert · Certificate of completion</p></article><article className="credential"><div className="credential-logo"><img src="/assets/logos/google.png" alt="Google" loading="lazy"/></div><span className="credential-type">COMPLETED COURSE</span><h3>Google AI Essentials</h3><p>Completed with sponsorship from Jobcare</p></article></div><Accordion type="single" collapsible className="additional-learning"><AccordionItem value="more-learning"><AccordionTrigger>More learning, qualifications & community</AccordionTrigger><AccordionContent><div className="learning-columns"><div><h3>Certifications & programmes</h3><ul><li>Zendesk Omnichannel Agent Specialist certification</li><li>Customer Support and Zendesk training through Jobcare</li><li>Jobnet and Kickstart programmes through Jobcare</li></ul></div><div><h3>Education</h3><p>MSc Data Analytics · Dublin Business School, 2020</p><p>Bachelor’s in Mathematics, Statistics & Computer Science · Loyola Academy, 2016</p></div><div><h3>Industry connections</h3><p>Jobcare networking events involving Zendesk, HubSpot, LinkedIn, Microsoft and Stripe.</p></div></div></AccordionContent></AccordionItem></Accordion></section>
 <section id="contact" className="contact-section"><div className="section-shell section-space contact-grid"><div><p className="eyebrow">LET’S CONNECT</p><h2>Your next release.<br/><em>My next challenge.</em></h2><p>I’m looking for SDET and QA opportunities where I can build automation, investigate failures and work closely with developers on release quality.</p><p>Based in Dublin, Ireland.</p><a className="contact-email" href="mailto:sravanthisunnam22@gmail.com">sravanthisunnam22@gmail.com</a><div className="social-links"><a href="https://www.linkedin.com/in/sravanthi-sunnam/" target="_blank" rel="noopener noreferrer"><ExternalLink size={18}/>LinkedIn</a><a href="https://github.com/sravanthisunnam22" target="_blank" rel="noopener noreferrer"><Code2 size={18}/>GitHub</a></div></div><form onSubmit={e=>{e.preventDefault();const data=new FormData(e.currentTarget);const subject='Portfolio enquiry from '+data.get('name');const body=String(data.get('message'))+'\n\nFrom: '+data.get('name')+'\nEmail: '+data.get('email');window.location.href='mailto:sravanthisunnam22@gmail.com?subject='+encodeURIComponent(subject)+'&body='+encodeURIComponent(body);setEmailStatus('Email draft requested. If your email app did not open, use the email address alongside.');}}><h3>Start a conversation</h3><label htmlFor="name">Your name</label><input id="name" name="name" required autoComplete="name" maxLength={120}/><label htmlFor="email">Your email</label><input id="email" name="email" type="email" required autoComplete="email" maxLength={200}/><label htmlFor="message">What would you like to discuss?</label><textarea id="message" name="message" rows={4} required maxLength={4000}/><button className="button contact-button" type="submit"><Mail size={18}/>Open email draft</button><p className="form-note">Opens your email app. No message is sent or stored by this website.</p><p role="status" className="form-note">{emailStatus}</p></form></div></section>
 </main><footer className="section-shell"><a className="brand" href="#top"><span className="monogram">ss<span>.</span></span><span>SRAVANTHI SUNNAM<br/><small>SDET & QA AUTOMATION</small></span></a><p>© 2026 Sravanthi Sunnam</p><a href="#top">Back to top</a></footer></>;
}
